# Generated by Django 3.2.7 on 2021-10-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-added_on']},
        ),
        migrations.AddField(
            model_name='photo',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=2020),
            preserve_default=False,
        ),
    ]
